import { User, Team, Project, Task, Comment, Notification, Activity, ApprovalRequest, TaskAnalytics, TeamAnalytics, ProductivityMetrics } from '@/types';
import { Department } from '@/features/departments/types';

// Re-export commonly used types for convenience
export type { User, Team, Project, Task };

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'super_admin',
    avatar: 'SJ',
    department: 'Executive',
    position: 'CEO',
    isActive: true,
    isOnline: true,
    skills: ['Leadership', 'Strategic Planning', 'Management'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    role: 'admin',
    avatar: 'MC',
    department: 'Engineering',
    position: 'Engineering Manager',
    isActive: true,
    isOnline: true,
    skills: ['System Design', 'Team Management', 'React', 'Node.js'],
    createdAt: new Date('2026-01-15'),
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    role: 'team_lead',
    avatar: 'ER',
    department: 'Engineering',
    position: 'Senior Developer',
    isActive: true,
    isOnline: false,
    skills: ['React', 'TypeScript', 'Frontend Architecture'],
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david.kim@company.com',
    role: 'employee',
    avatar: 'DK',
    department: 'Engineering',
    position: 'Frontend Developer',
    isActive: true,
    isOnline: true,
    skills: ['UI/UX', 'CSS', 'React'],
    createdAt: new Date('2026-02-15'),
  },
  {
    id: '5',
    name: 'Lisa Martinez',
    email: 'lisa.martinez@company.com',
    role: 'employee',
    avatar: 'LM',
    department: 'Engineering',
    position: 'Backend Developer',
    isActive: true,
    createdAt: new Date('2026-03-01'),
  },
  {
    id: '6',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    role: 'admin',
    avatar: 'JW',
    department: 'Product',
    position: 'Product Manager',
    isActive: true,
    createdAt: new Date('2026-01-20'),
  },
  {
    id: '7',
    name: 'Robert Taylor',
    email: 'robert.taylor@company.com',
    role: 'admin',
    avatar: 'RT',
    department: 'Product',
    position: 'Product Director',
    isActive: true,
    isOnline: true,
    skills: ['Product Strategy', 'Roadmapping', 'Agile'],
    createdAt: new Date('2026-02-15'),
  },
  {
    id: '99',
    name: 'Alex Morgan',
    email: 'alex.morgan@company.com',
    role: 'senior_developer',
    avatar: 'AM',
    department: 'Engineering',
    position: 'Senior Developer',
    isActive: true,
    isOnline: true,
    skills: ['System Architecture', 'Node.js', 'React', 'DevOps'],
    createdAt: new Date('2026-02-20'),
  },
];

// Mock Teams
export const mockTeams: Team[] = [
  {
    id: '1',
    name: 'Engineering Team Alpha',
    description: 'Core platform development team',
    leadId: '3',
    memberIds: ['3', '4', '5'],
    projectIds: ['1', '2'],
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-10'),
    status: 'active',
    avatar: 'bg-blue-100 text-blue-600',
  },
  {
    id: '2',
    name: 'Product Team',
    description: 'Product strategy and design',
    leadId: '6',
    memberIds: ['6'],
    projectIds: ['3'],
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-02-05'),
    status: 'active',
    avatar: 'bg-purple-100 text-purple-600',
  },
  {
    id: '3',
    name: 'QA Team',
    description: 'Quality Assurance and Testing',
    leadId: '6', // Reusing James for now
    memberIds: ['4', '5'],
    projectIds: ['1'],
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-05'),
    status: 'idle',
    avatar: 'bg-green-100 text-green-600',
  },
];

// Extended Projects with full metadata
import type { ExtendedProject,Phase } from '@/features/projects/types';

export const extendedProjects: ExtendedProject[] = [
  {
    id: '1',
    name: 'Platform Modernization',
    description: 'Upgrade core infrastructure and migrate to microservices architecture',
    status: 'active',
    health: 'yellow',
    progress: 65,
    startDate: new Date('2026-02-01'),
    endDate: new Date('2026-06-30'),
    members: [
      { userId: '2', name: 'Michael Chen', avatar: 'MC', role: 'owner', joinedAt: new Date('2026-02-01') },
      { userId: '3', name: 'Emily Rodriguez', avatar: 'ER', role: 'manager', joinedAt: new Date('2026-02-01') },
      { userId: '4', name: 'David Kim', avatar: 'DK', role: 'member', joinedAt: new Date('2026-02-05') },
      { userId: '5', name: 'Lisa Martinez', avatar: 'LM', role: 'member', joinedAt: new Date('2026-02-05') },
    ],
    phases: [
      { id: 'p1', name: 'Planning', order: 1, color: '#3B82F6', status: 'completed', taskCount: 3, completionPercentage: 100 },
      { id: 'p2', name: 'Design', order: 2, color: '#8B5CF6', status: 'completed', taskCount: 2, completionPercentage: 100 },
      { id: 'p3', name: 'Development', order: 3, color: '#10B981', status: 'active', taskCount: 4, completionPercentage: 60 },
      { id: 'p4', name: 'Testing', order: 4, color: '#F59E0B', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
      { id: 'p5', name: 'Deployment', order: 5, color: '#EF4444', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
    ],
    templateId: 'software-dev',
    tags: ['infrastructure', 'backend', 'migration'],
    isStarred: true,
    taskCount: 6,
    completedTaskCount: 1,
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Build native iOS and Android applications',
    status: 'active',
    health: 'green',
    progress: 35,
    startDate: new Date('2026-03-01'),
    endDate: new Date('2026-08-31'),
    members: [
      { userId: '2', name: 'Michael Chen', avatar: 'MC', role: 'owner', joinedAt: new Date('2026-03-01') },
      { userId: '4', name: 'David Kim', avatar: 'DK', role: 'member', joinedAt: new Date('2026-03-01') },
    ],
    phases: [
      { id: '2p1', name: 'Planning', order: 1, color: '#3B82F6', status: 'completed', taskCount: 2, completionPercentage: 100 },
      { id: '2p2', name: 'Design', order: 2, color: '#8B5CF6', status: 'active', taskCount: 3, completionPercentage: 40 },
      { id: '2p3', name: 'Development', order: 3, color: '#10B981', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
      { id: '2p4', name: 'Testing', order: 4, color: '#F59E0B', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
      { id: '2p5', name: 'Deployment', order: 5, color: '#EF4444', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
    ],
    templateId: 'software-dev',
    tags: ['mobile', 'ios', 'android'],
    isStarred: false,
    taskCount: 3,
    completedTaskCount: 0,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: '3',
    name: 'Q2 Product Roadmap',
    description: 'Plan and execute Q2 2024 product initiatives',
    status: 'active',
    health: 'green',
    progress: 45,
    startDate: new Date('2026-04-01'),
    members: [
      { userId: '6', name: 'James Wilson', avatar: 'JW', role: 'owner', joinedAt: new Date('2026-03-20') },
    ],
    phases: [
      { id: '3p1', name: 'Research', order: 1, color: '#3B82F6', status: 'active', taskCount: 1, completionPercentage: 20 },
      { id: '3p2', name: 'Strategy', order: 2, color: '#8B5CF6', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
      { id: '3p3', name: 'Creative', order: 3, color: '#10B981', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
      { id: '3p4', name: 'Launch', order: 4, color: '#F59E0B', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
      { id: '3p5', name: 'Analysis', order: 5, color: '#6366F1', status: 'upcoming', taskCount: 0, completionPercentage: 0 },
    ],
    templateId: 'marketing',
    tags: ['planning', 'strategy'],
    isStarred: true,
    taskCount: 1,
    completedTaskCount: 0,
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-25'),
    riskScore: 'medium',
    budget: { total: 75000, used: 25000, currency: 'USD' },
    ownerId: '3',
    milestones: [
        { id: 'm8', name: 'Research Phase', date: new Date('2026-03-15'), status: 'completed' },
        { id: 'm9', name: 'Prototype', date: new Date('2026-05-01'), status: 'pending' }
    ],
  },
  {
    id: '4',
    name: 'Legacy System Migration',
    description: 'Migrate data from old CRM to new platform',
    status: 'completed',
    health: 'green',
    progress: 100,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-02-28'),
    members: [
      { userId: '2', name: 'Michael Chen', avatar: 'MC', role: 'owner', joinedAt: new Date('2026-01-01') },
      { userId: '5', name: 'Lisa Martinez', avatar: 'LM', role: 'member', joinedAt: new Date('2026-01-01') },
    ],
    phases: [
      { id: '4p1', name: 'Planning', order: 1, color: '#3B82F6', status: 'completed', taskCount: 2, completionPercentage: 100 },
      { id: '4p2', name: 'Design', order: 2, color: '#8B5CF6', status: 'completed', taskCount: 1, completionPercentage: 100 },
      { id: '4p3', name: 'Development', order: 3, color: '#10B981', status: 'completed', taskCount: 3, completionPercentage: 100 },
      { id: '4p4', name: 'Testing', order: 4, color: '#F59E0B', status: 'completed', taskCount: 2, completionPercentage: 100 },
      { id: '4p5', name: 'Deployment', order: 5, color: '#EF4444', status: 'completed', taskCount: 1, completionPercentage: 100 },
    ],
    templateId: 'software-dev',
    tags: ['migration', 'data', 'legacy'],
    isStarred: false,
    taskCount: 9,
    completedTaskCount: 9,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-28'),
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Platform Modernization',
    description: 'Upgrade core infrastructure and migrate to microservices architecture',
    status: 'active',
    teamId: '1',
    ownerId: '2',
    startDate: new Date('2026-02-01'),
    endDate: new Date('2026-06-30'),
    progress: 65,
    priority: 'high',
    tags: ['infrastructure', 'backend', 'migration'],
    phases: [],
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Build native iOS and Android applications',
    status: 'active',
    teamId: '1',
    ownerId: '2',
    startDate: new Date('2026-03-01'),
    endDate: new Date('2026-08-31'),
    progress: 35,
    priority: 'medium',
    tags: ['mobile', 'ios', 'android'],
    phases: [],
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: '3',
    name: 'Q2 Product Roadmap',
    description: 'Plan and execute Q2 2024 product initiatives',
    status: 'planning',
    teamId: '2',
    ownerId: '6',
    startDate: new Date('2026-04-01'),
    progress: 10,
    priority: 'high',
    tags: ['ai', 'financial', 'core'],
    phases: [],
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-03-25'),
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design API Gateway Architecture',
    description: 'Create detailed architecture diagrams and documentation for the new API gateway implementation',
    status: 'in_progress',
    priority: 'critical',
    projectId: '1',
    assigneeIds: ['3', '4'],
    creatorId: '2',
    dueDate: new Date('2026-02-20'),
    startDate: new Date('2026-02-10'),
    estimatedHours: 20,
    actualHours: 12,
    tags: ['architecture', 'api', 'documentation'],
    attachments: [
      {
        id: 'att1',
        name: 'api-gateway-draft.pdf',
        url: 'file:///C:/Users/Amol/Downloads/Linux%20Command%20Cheat%20Sheet%20(beginner%20%E2%86%92%20Production).pdf',
        type: 'application/pdf',
        size: 2048000,
        uploadedBy: '3',
        uploadedAt: new Date('2026-02-12'),
      },
    ],
    comments: [],
    subtasks: [
      { id: 's1', title: 'Research existing solutions', isCompleted: true, createdAt: new Date('2026-02-10') },
      { id: 's2', title: 'Create architecture diagram', isCompleted: true, createdAt: new Date('2026-02-10') },
      { id: 's3', title: 'Document API specifications', isCompleted: false, createdAt: new Date('2026-02-10') },
      { id: 's4', title: 'Review with team', isCompleted: false, createdAt: new Date('2026-02-10') },
    ],
    dependencies: [],
    position: 1,
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: '2',
    title: 'Implement User Authentication Service',
    description: 'Build microservice for user authentication with OAuth2 and JWT support',
    status: 'todo',
    priority: 'high',
    projectId: '1',
    assigneeIds: ['5'],
    creatorId: '2',
    dueDate: new Date('2026-02-25'),
    estimatedHours: 40,
    tags: ['backend', 'security', 'microservices'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's5', title: 'Setup service scaffolding', isCompleted: false, createdAt: new Date('2026-02-15') },
      { id: 's6', title: 'Implement OAuth2 flow', isCompleted: false, createdAt: new Date('2026-02-15') },
      { id: 's7', title: 'Add JWT token generation', isCompleted: false, createdAt: new Date('2026-02-15') },
      { id: 's8', title: 'Write unit tests', isCompleted: false, createdAt: new Date('2026-02-15') },
    ],
    dependencies: ['1'],
    position: 2,
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: '3',
    title: 'UI Component Library Setup',
    description: 'Create reusable component library for mobile apps',
    status: 'in_progress',
    priority: 'medium',
    projectId: '2',
    assigneeIds: ['4'],
    creatorId: '2',
    dueDate: new Date('2026-03-10'),
    startDate: new Date('2026-03-01'),
    estimatedHours: 30,
    actualHours: 18,
    tags: ['frontend', 'mobile', 'components'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's9', title: 'Setup Storybook', isCompleted: true, createdAt: new Date('2026-03-01') },
      { id: 's10', title: 'Create base components', isCompleted: true, createdAt: new Date('2026-03-01') },
      { id: 's11', title: 'Add theming support', isCompleted: false, createdAt: new Date('2026-03-01') },
    ],
    dependencies: [],
    position: 1,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-08'),
  },
  {
    id: '4',
    title: 'Database Migration Script',
    description: 'Write migration scripts for moving data from legacy system to new database',
    status: 'review',
    priority: 'high',
    projectId: '1',
    assigneeIds: ['5'],
    creatorId: '3',
    dueDate: new Date('2026-02-18'),
    startDate: new Date('2026-02-08'),
    estimatedHours: 25,
    actualHours: 24,
    tags: ['database', 'migration', 'backend'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's12', title: 'Analyze legacy schema', isCompleted: true, createdAt: new Date('2026-02-08') },
      { id: 's13', title: 'Write migration scripts', isCompleted: true, createdAt: new Date('2026-02-08') },
      { id: 's14', title: 'Test on staging environment', isCompleted: true, createdAt: new Date('2026-02-08') },
    ],
    dependencies: [],
    position: 1,
    createdAt: new Date('2026-02-08'),
    updatedAt: new Date('2026-02-17'),
  },
  {
    id: '5',
    title: 'Code Review Guidelines',
    description: 'Document team code review standards and best practices',
    status: 'done',
    priority: 'low',
    projectId: '1',
    assigneeIds: ['3'],
    creatorId: '2',
    dueDate: new Date('2026-02-10'),
    startDate: new Date('2026-02-05'),
    estimatedHours: 8,
    actualHours: 6,
    tags: ['documentation', 'process'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's15', title: 'Draft guidelines', isCompleted: true, createdAt: new Date('2026-02-05') },
      { id: 's16', title: 'Get team feedback', isCompleted: true, createdAt: new Date('2026-02-05') },
      { id: 's17', title: 'Publish to wiki', isCompleted: true, createdAt: new Date('2026-02-05') },
    ],
    dependencies: [],
    position: 1,
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: '6',
    title: 'Performance Optimization',
    description: 'Identify and fix performance bottlenecks in API endpoints',
    status: 'blocked',
    priority: 'medium',
    projectId: '1',
    assigneeIds: ['4'],
    creatorId: '3',
    dueDate: new Date('2026-02-28'),
    estimatedHours: 35,
    tags: ['performance', 'backend', 'optimization'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's18', title: 'Run performance profiling', isCompleted: true, createdAt: new Date('2026-02-16') },
      { id: 's19', title: 'Identify slow queries', isCompleted: false, createdAt: new Date('2026-02-16') },
    ],
    dependencies: ['4'],
    position: 1,
    createdAt: new Date('2026-02-16'),
    updatedAt: new Date('2026-02-16'),
  },
  // Additional TO DO tasks
  {
    id: '7',
    title: 'Setup CI/CD Pipeline',
    description: 'Configure automated build and deployment pipeline using GitHub Actions',
    status: 'todo',
    priority: 'high',
    projectId: '1',
    assigneeIds: ['5'],
    creatorId: '2',
    dueDate: new Date('2026-03-05'),
    estimatedHours: 16,
    tags: ['devops', 'automation', 'ci-cd'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's20', title: 'Setup GitHub Actions workflows', isCompleted: false, createdAt: new Date('2026-02-18') },
      { id: 's21', title: 'Configure staging deployment', isCompleted: false, createdAt: new Date('2026-02-18') },
      { id: 's22', title: 'Setup production deployment', isCompleted: false, createdAt: new Date('2026-02-18') },
    ],
    dependencies: [],
    position: 3,
    createdAt: new Date('2026-02-18'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: '8',
    title: 'API Documentation with Swagger',
    description: 'Generate comprehensive API documentation using Swagger/OpenAPI',
    status: 'todo',
    priority: 'medium',
    projectId: '1',
    assigneeIds: ['4'],
    creatorId: '3',
    dueDate: new Date('2026-03-12'),
    estimatedHours: 12,
    tags: ['documentation', 'api'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's23', title: 'Install Swagger tools', isCompleted: false, createdAt: new Date('2026-02-19') },
      { id: 's24', title: 'Document all endpoints', isCompleted: false, createdAt: new Date('2026-02-19') },
    ],
    dependencies: ['1'],
    position: 4,
    createdAt: new Date('2026-02-19'),
    updatedAt: new Date('2026-02-19'),
  },
  {
    id: '9',
    title: 'Error Handling & Logging System',
    description: 'Implement centralized error handling and structured logging',
    status: 'todo',
    priority: 'high',
    projectId: '1',
    assigneeIds: ['3'],
    creatorId: '2',
    dueDate: new Date('2026-03-08'),
    estimatedHours: 20,
    tags: ['backend', 'logging', 'error-handling'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's25', title: 'Setup logging framework', isCompleted: false, createdAt: new Date('2026-02-20') },
      { id: 's26', title: 'Create error handler middleware', isCompleted: false, createdAt: new Date('2026-02-20') },
      { id: 's27', title: 'Add log aggregation', isCompleted: false, createdAt: new Date('2026-02-20') },
    ],
    dependencies: [],
    position: 5,
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  // Additional IN PROGRESS tasks
  {
    id: '10',
    title: 'User Dashboard Implementation',
    description: 'Build responsive user dashboard with charts and analytics',
    status: 'in_progress',
    priority: 'high',
    projectId: '2',
    assigneeIds: ['4'],
    creatorId: '2',
    dueDate: new Date('2026-03-15'),
    startDate: new Date('2026-02-20'),
    estimatedHours: 32,
    actualHours: 15,
    tags: ['frontend', 'dashboard', 'analytics'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's28', title: 'Design dashboard layout', isCompleted: true, createdAt: new Date('2026-02-20') },
      { id: 's29', title: 'Implement chart components', isCompleted: true, createdAt: new Date('2026-02-20') },
      { id: 's30', title: 'Add data filters', isCompleted: false, createdAt: new Date('2026-02-20') },
      { id: 's31', title: 'Optimize performance', isCompleted: false, createdAt: new Date('2026-02-20') },
    ],
    dependencies: ['3'],
    position: 2,
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-25'),
  },
  {
    id: '11',
    title: 'Notification System',
    description: 'Implement real-time notification system with WebSocket support',
    status: 'in_progress',
    priority: 'medium',
    projectId: '1',
    assigneeIds: ['5'],
    creatorId: '3',
    dueDate: new Date('2026-03-10'),
    startDate: new Date('2026-02-21'),
    estimatedHours: 24,
    actualHours: 10,
    tags: ['backend', 'websocket', 'real-time'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's32', title: 'Setup WebSocket server', isCompleted: true, createdAt: new Date('2026-02-21') },
      { id: 's33', title: 'Create notification handlers', isCompleted: false, createdAt: new Date('2026-02-21') },
      { id: 's34', title: 'Add email notifications', isCompleted: false, createdAt: new Date('2026-02-21') },
    ],
    dependencies: [],
    position: 3,
    createdAt: new Date('2026-02-21'),
    updatedAt: new Date('2026-02-24'),
  },
  // Additional REVIEW tasks
  {
    id: '12',
    title: 'Security Audit & Vulnerability Scan',
    description: 'Conduct comprehensive security audit and fix vulnerabilities',
    status: 'review',
    priority: 'critical',
    projectId: '1',
    assigneeIds: ['3', '5'],
    creatorId: '2',
    dueDate: new Date('2026-02-22'),
    startDate: new Date('2026-02-10'),
    estimatedHours: 30,
    actualHours: 28,
    tags: ['security', 'audit', 'testing'],
    attachments: [
      {
        id: 'att2',
        name: 'security-audit-report.pdf',
        url: '/files/security-audit-report.pdf',
        type: 'application/pdf',
        size: 3145728,
        uploadedBy: '3',
        uploadedAt: new Date('2026-02-21'),
      },
    ],
    comments: [],
    subtasks: [
      { id: 's35', title: 'Run vulnerability scanner', isCompleted: true, createdAt: new Date('2026-02-10') },
      { id: 's36', title: 'Fix critical vulnerabilities', isCompleted: true, createdAt: new Date('2026-02-10') },
      { id: 's37', title: 'Document security measures', isCompleted: true, createdAt: new Date('2026-02-10') },
      { id: 's38', title: 'Peer review', isCompleted: false, createdAt: new Date('2026-02-10') },
    ],
    dependencies: [],
    position: 2,
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-21'),
  },
  {
    id: '13',
    title: 'Payment Gateway Integration',
    description: 'Integrate Stripe payment gateway for subscription management',
    status: 'review',
    priority: 'high',
    projectId: '2',
    assigneeIds: ['5'],
    creatorId: '2',
    dueDate: new Date('2026-03-20'),
    startDate: new Date('2026-03-05'),
    estimatedHours: 28,
    actualHours: 26,
    tags: ['payment', 'integration', 'backend'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's39', title: 'Setup Stripe account', isCompleted: true, createdAt: new Date('2026-03-05') },
      { id: 's40', title: 'Implement payment API', isCompleted: true, createdAt: new Date('2026-03-05') },
      { id: 's41', title: 'Add webhook handlers', isCompleted: true, createdAt: new Date('2026-03-05') },
      { id: 's42', title: 'Test payment flows', isCompleted: true, createdAt: new Date('2026-03-05') },
    ],
    dependencies: [],
    position: 3,
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-18'),
  },
  // Additional DONE tasks
  {
    id: '14',
    title: 'Project Kickoff Meeting',
    description: 'Initial team meeting to discuss project scope and requirements',
    status: 'done',
    priority: 'high',
    projectId: '1',
    assigneeIds: ['2', '3', '4', '5'],
    creatorId: '2',
    dueDate: new Date('2026-02-01'),
    startDate: new Date('2026-02-01'),
    estimatedHours: 2,
    actualHours: 2,
    tags: ['meeting', 'planning'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's43', title: 'Prepare agenda', isCompleted: true, createdAt: new Date('2026-01-30') },
      { id: 's44', title: 'Conduct meeting', isCompleted: true, createdAt: new Date('2026-01-30') },
      { id: 's45', title: 'Share meeting notes', isCompleted: true, createdAt: new Date('2026-01-30') },
    ],
    dependencies: [],
    position: 2,
    createdAt: new Date('2026-01-30'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: '15',
    title: 'Development Environment Setup',
    description: 'Setup local development environment for all team members',
    status: 'done',
    priority: 'high',
    projectId: '1',
    assigneeIds: ['3'],
    creatorId: '2',
    dueDate: new Date('2026-02-03'),
    startDate: new Date('2026-02-01'),
    estimatedHours: 8,
    actualHours: 7,
    tags: ['setup', 'devops'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's46', title: 'Install required software', isCompleted: true, createdAt: new Date('2026-02-01') },
      { id: 's47', title: 'Configure IDE settings', isCompleted: true, createdAt: new Date('2026-02-01') },
      { id: 's48', title: 'Setup version control', isCompleted: true, createdAt: new Date('2026-02-01') },
      { id: 's49', title: 'Document setup process', isCompleted: true, createdAt: new Date('2026-02-01') },
    ],
    dependencies: [],
    position: 3,
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-03'),
  },
  {
    id: '16',
    title: 'Design System Color Palette',
    description: 'Define color schemes and brand guidelines for the application',
    status: 'done',
    priority: 'medium',
    projectId: '2',
    assigneeIds: ['4'],
    creatorId: '6',
    dueDate: new Date('2026-03-03'),
    startDate: new Date('2026-03-01'),
    estimatedHours: 6,
    actualHours: 5,
    tags: ['design', 'branding', 'ui'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's50', title: 'Research color trends', isCompleted: true, createdAt: new Date('2026-03-01') },
      { id: 's51', title: 'Create color palette', isCompleted: true, createdAt: new Date('2026-03-01') },
      { id: 's52', title: 'Get approval from stakeholders', isCompleted: true, createdAt: new Date('2026-03-01') },
    ],
    dependencies: [],
    position: 4,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-03'),
  },
  {
    id: '17',
    title: 'Database Schema Design',
    description: 'Design normalized database schema for core entities',
    status: 'done',
    priority: 'critical',
    projectId: '1',
    assigneeIds: ['5'],
    creatorId: '2',
    dueDate: new Date('2026-02-07'),
    startDate: new Date('2026-02-02'),
    estimatedHours: 16,
    actualHours: 14,
    tags: ['database', 'design', 'backend'],
    attachments: [
      {
        id: 'att3',
        name: 'db-schema-diagram.png',
        url: '/files/db-schema-diagram.png',
        type: 'image/png',
        size: 1024000,
        uploadedBy: '5',
        uploadedAt: new Date('2026-02-06'),
      },
    ],
    comments: [],
    subtasks: [
      { id: 's53', title: 'Identify entities and relationships', isCompleted: true, createdAt: new Date('2026-02-02') },
      { id: 's54', title: 'Create ER diagram', isCompleted: true, createdAt: new Date('2026-02-02') },
      { id: 's55', title: 'Normalize schema', isCompleted: true, createdAt: new Date('2026-02-02') },
      { id: 's56', title: 'Review with team', isCompleted: true, createdAt: new Date('2026-02-02') },
    ],
    dependencies: [],
    position: 5,
    createdAt: new Date('2026-02-02'),
    updatedAt: new Date('2026-02-07'),
  },
  {
    id: '18',
    title: 'Unit Test Coverage Setup',
    description: 'Setup testing framework and achieve 80% code coverage',
    status: 'done',
    priority: 'medium',
    projectId: '1',
    assigneeIds: ['3', '4'],
    creatorId: '2',
    dueDate: new Date('2026-02-12'),
    startDate: new Date('2026-02-08'),
    estimatedHours: 14,
    actualHours: 15,
    tags: ['testing', 'quality'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's57', title: 'Setup Jest/testing library', isCompleted: true, createdAt: new Date('2026-02-08') },
      { id: 's58', title: 'Write test cases', isCompleted: true, createdAt: new  Date('2024-02-08') },
      { id: 's59', title: 'Configure coverage reports', isCompleted: true, createdAt: new Date('2026-02-08') },
    ],
    dependencies: [],
    position: 6,
    createdAt: new Date('2026-02-08'),
    updatedAt: new Date('2026-02-12'),
  },
  {
    id: '19',
    title: 'Marketing Campaign Planning',
    description: 'Plan Q2 marketing campaigns and content strategy',
    status: 'in_progress',
    priority: 'medium',
    projectId: '3',
    assigneeIds: ['6'],
    creatorId: '6',
    dueDate: new Date('2026-04-15'),
    startDate: new Date('2026-03-25'),
    estimatedHours: 20,
    actualHours: 8,
    tags: ['marketing', 'strategy', 'planning'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's60', title: 'Define target audience', isCompleted: true, createdAt: new Date('2026-03-25') },
      { id: 's61', title: 'Create content calendar', isCompleted: false, createdAt: new Date('2026-03-25') },
      { id: 's62', title: 'Set marketing budget', isCompleted: false, createdAt: new Date('2026-03-25') },
    ],
    dependencies: [],
    position: 1,
    createdAt: new Date('2026-03-25'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: '20',
    title: 'Mobile App Navigation Flow',
    description: 'Design and implement navigation structure for mobile app',
    status: 'todo',
    priority: 'high',
    projectId: '2',
    assigneeIds: ['4'],
    creatorId: '2',
    dueDate: new Date('2026-03-22'),
    estimatedHours: 18,
    tags: ['mobile', 'navigation', 'ux'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 's63', title: 'Create navigation wireframes', isCompleted: false, createdAt: new Date('2026-02-22') },
      { id: 's64', title: 'Implement navigation library', isCompleted: false, createdAt: new Date('2026-02-22') },
      { id: 's65', title: 'Add deep linking support', isCompleted: false, createdAt: new Date('2026-02-22') },
    ],
    dependencies: ['3'],
    position: 2,
    createdAt: new Date('2026-02-22'),
    updatedAt: new Date('2026-02-22'),
  },
];

// Mock Comments
export const mockComments: Comment[] = [
  {
    id: '1',
    taskId: '1',
    userId: '3',
    content: 'Started working on the architecture diagram. @David Kim can you help with the API specifications?',
    mentions: ['4'],
    reactions: [
      { emoji: '👍', userIds: ['4', '2'] },
    ],
    createdAt: new Date('2026-02-12T10:30:00'),
    updatedAt: new Date('2026-02-12T10:30:00'),
  },
  {
    id: '2',
    taskId: '1',
    userId: '4',
    content: 'Sure! I\'ll start documenting the API specs today.',
    mentions: [],
    parentId: '1',
    reactions: [],
    createdAt: new Date('2026-02-12T11:15:00'),
    updatedAt: new Date('2026-02-12T11:15:00'),
  },
  {
    id: '3',
    taskId: '4',
    userId: '3',
    content: 'Migration scripts look good! Just need one more review before we can deploy.',
    mentions: [],
    reactions: [
      { emoji: '✅', userIds: ['5'] },
    ],
    createdAt: new Date('2026-02-17T14:20:00'),
    updatedAt: new Date('2026-02-17T14:20:00'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '4',
    type: 'task_assigned',
    title: 'New task assigned',
    message: 'Emily Rodriguez assigned you to "Design API Gateway Architecture"',
    taskId: '1',
    isRead: false,
    actionUrl: '/dashboard/employee?task=1',
    createdAt: new Date('2026-02-10T09:00:00'),
  },
  {
    id: '2',
    userId: '4',
    type: 'comment_mention',
    title: 'You were mentioned',
    message: 'Emily Rodriguez mentioned you in a comment',
    taskId: '1',
    isRead: false,
    actionUrl: '/dashboard/employee?task=1',
    createdAt: new Date('2026-02-12T10:30:00'),
  },
  {
    id: '3',
    userId: '5',
    type: 'task_due_soon',
    title: 'Task due soon',
    message: 'Task "Implement User Authentication Service" is due in 2 days',
    taskId: '2',
    isRead: true,
    actionUrl: '/dashboard/employee?task=2',
    createdAt: new Date('2026-02-23T08:00:00'),
  },
  {
    id: '4',
    userId: '3',
    type: 'approval_request',
    title: 'Approval request',
    message: 'David Kim requested deadline extension for "Performance Optimization"',
    taskId: '6',
    isRead: false,
    actionUrl: '/dashboard/team-lead?approval=1',
    createdAt: new Date('2026-02-18T15:30:00'),
  },
];

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'task_created',
    userId: '2',
    taskId: '1',
    projectId: '1',
    metadata: { taskTitle: 'Design API Gateway Architecture' },
    createdAt: new Date('2026-02-10T08:00:00'),
  },
  {
    id: '2',
    type: 'task_assigned',
    userId: '2',
    taskId: '1',
    metadata: { assignedTo: ['3', '4'] },
    createdAt: new Date('2026-02-10T08:05:00'),
  },
  {
    id: '3',
    type: 'status_changed',
    userId: '3',
    taskId: '1',
    metadata: { from: 'todo', to: 'in_progress' },
    createdAt: new Date('2026-02-10T09:30:00'),
  },
  {
    id: '4',
    type: 'comment_added',
    userId: '3',
    taskId: '1',
    metadata: { commentId: '1' },
    createdAt: new Date('2026-02-12T10:30:00'),
  },
  {
    id: '5',
    type: 'task_completed',
    userId: '3',
    taskId: '5',
    projectId: '1',
    metadata: { taskTitle: 'Code Review Guidelines' },
    createdAt: new Date('2026-02-10T16:00:00'),
  },
];

// Mock Approval Requests
export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: '1',
    type: 'deadline_extension',
    requesterId: '4',
    approverId: '3',
    taskId: '6',
    reason: 'Waiting for database migration to complete before running performance tests',
    status: 'pending',
    createdAt: new Date('2026-02-18T15:30:00'),
  },
  {
    id: '2',
    type: 'resource_request',
    requesterId: '5',
    approverId: '2',
    projectId: '1',
    reason: 'Need additional cloud resources for testing environment',
    status: 'approved',
    responseMessage: 'Approved. Resources provisioned.',
    createdAt: new Date('2026-02-15T10:00:00'),
    respondedAt: new Date('2026-02-15T14:30:00'),
  },
];

// Mock Analytics
export const mockTaskAnalytics: TaskAnalytics = {
  totalTasks: 6,
  completedTasks: 1,
  inProgressTasks: 2,
  overdueTasks: 0,
  completionRate: 16.7,
  averageCompletionTime: 48,
  tasksByPriority: {
    critical: 1,
    high: 2,
    medium: 2,
    low: 1,
  },
  tasksByStatus: {
    todo: 1,
    in_progress: 2,
    review: 1,
    done: 1,
    blocked: 1,
  },
};

export const mockTeamAnalytics: TeamAnalytics = {
  totalMembers: 3,
  activeProjects: 2,
  completedProjects: 0,
  totalTasks: 6,
  completionRate: 16.7,
  memberWorkload: [
    { userId: '3', activeTasks: 2, completedTasks: 1 },
    { userId: '4', activeTasks: 2, completedTasks: 0 },
    { userId: '5', activeTasks: 2, completedTasks: 0 },
  ],
};

export const mockProductivityMetrics: ProductivityMetrics[] = [
  { date: new Date('2026-02-05'), tasksCompleted: 2, tasksCreated: 1, activeUsers: 5 },
  { date: new Date('2026-02-06'), tasksCompleted: 1, tasksCreated: 3, activeUsers: 6 },
  { date: new Date('2026-02-07'), tasksCompleted: 3, tasksCreated: 2, activeUsers: 5 },
  { date: new Date('2026-02-08'), tasksCompleted: 2, tasksCreated: 4, activeUsers: 6 },
  { date: new Date('2026-02-09'), tasksCompleted: 4, tasksCreated: 2, activeUsers: 5 },
  { date: new Date('2026-02-10'), tasksCompleted: 1, tasksCreated: 1, activeUsers: 6 },
  { date: new Date('2026-02-11'), tasksCompleted: 0, tasksCreated: 2, activeUsers: 4 },
];

// Helper functions
export const getUserById = (id: string): User | undefined => {
  return mockUsers.find(user => user.id === id);
};

export const getTasksByProject = (projectId: string): Task[] => {
  return mockTasks.filter(task => task.projectId === projectId);
};

export const getTasksByAssignee = (userId: string): Task[] => {
  return mockTasks.filter(task => task.assigneeIds.includes(userId));
};

export const getCommentsByTask = (taskId: string): Comment[] => {
  return mockComments.filter(comment => comment.taskId === taskId);
};

export const getNotificationsByUser = (userId: string): Notification[] => {
  return mockNotifications.filter(notif => notif.userId === userId);
};

export const getUnreadNotificationCount = (userId: string): number => {
  return mockNotifications.filter(notif => notif.userId === userId && !notif.isRead).length;
};

// Mock Departments
export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Engineering',
    description: 'Software development and technical infrastructure',
    managerId: '2',
    employeeIds: ['2', '3', '4', '5'],
    budget: 500000,
    createdAt: new Date('2026-01-01'),
    isActive: true,
  },
  {
    id: '2',
    name: 'Product',
    description: 'Product management and strategy',
    managerId: '6',
    employeeIds: ['6'],
    budget: 200000,
    createdAt: new Date('2026-01-01'),
    isActive: true,
  },
  {
    id: '3',
    name: 'Executive',
    description: 'Company leadership and governance',
    managerId: '1',
    employeeIds: ['1'],
    budget: 1000000,
    createdAt: new Date('2026-01-01'),
    isActive: true,
  },
];
